package com.chatapp.config;

public class JwtConstants {

	public static final String JWT_HEADER="Authorization";
	public static final String SECRET_KEY="dfgdjhtsbdfvwdsfegbgfbrtvghjvjhbjhbjhfbwjhbfjhbjhqwsdjhwvdjhqvdjhwvqjhdbhjwebdhjwedhjwevfhvwejhfvhwevdhsjhaqbhhwbbacfgfgczadsjwnjednbjwebndejdbjwebdjhbfjbewrjhbfjerbjhfbrebfbjerbfjrbjbfjbjhhtrshz";
}
